name: Build and push

on:
  push:
    branches: [master]
    paths:
      - Dockerfile
      - .github/workflows/build_and_push.yml
    tags:
      - "*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/asterisk-quectel-rpi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
